# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - master

jobs:
  # - job: Windows_VS2017_x86
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   steps:
  - job: Ubuntu_1604_Apt
    pool:
      vmImage: 'Ubuntu 16.04'
    containerImage: ubuntu:18.04
    steps:
      - script: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial
          sudo apt-get update
          sudo apt-get install -y cmake extra-cmake-modules qt511-meta-minimal qt511location qt511sensors qt511webchannel libxcomposite-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libhyphen-dev gperf ninja-build libgl-dev
      displayName: Apt install dependencies
      - script: |
          mkdir build && cd build
          export QTDIR="/opt/qt512"
          source ${QTDIR}/bin/qt512-env.sh
          cmake -DPORT=Qt -DCMAKE_INSTALL_PREFIX="${BUILD_STAGINGDIRECTORY}" -G Ninja -DCMAKE_MAKE_PROGRAM=$(which ninja) ..
      displayName: Configure build
      - task: CMake@1
        inputs:
          workingDirectory: 'build'
          cmakeArgs: '--build .'
        displayName: Build QtWebkit
